config/routes.rb
Rails.application.routes.draw do

  resources :coordinators, only: [:index, :show, :edit, :update]

  resources :enterprises, only: [:index, :show, :edit, :update] do
    resources :drivers
    resources :cars, except: :index
    resources :car_drivers
  end


  resources :tutors, only: [:index, :show, :edit, :update] do
    # get 'students/get_location'
    resources :students do
      resources :trips, only: :index
    end
  end

  root 'homes#index'

  get 'students/get_location'

  get 'students/coord_logic'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
  :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

  belongs_to :enterprise, class_name: 'Enterprise', foreign_key: 'user_id'

end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :region
  # has_many :tutors
  # has_many :students

  # has_many :students
  # , class_name: 'Student', foreign_key: 'student_id'

end

app/models/coordinator.rb
class Coordinator < User

  # has_many :schools

end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/driver.rb
class Driver < User

  belongs_to :enterprise, class_name: 'Enterprise', foreign_key: 'enterprise_id'

  # has_many :car_drivers, class_name: 'CarDriver', foreign_key: 'driver_id'

  # has_many :cars, through: :car_drivers

  # has_many :schools


end

app/models/enterprise.rb
class Enterprise < User

  has_many :drivers, class_name: 'Driver', foreign_key: 'enterprise_id', dependent: :destroy

  has_many :cars, class_name: 'Car', foreign_key: 'user_id', dependent: :destroy

  # has_many :car_drivers, class_name: 'CarDriver', foreign_key: 'driver_id', dependent: :destroy

  # has_many :schools



end

app/models/point.rb
class Point < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
end

app/models/school.rb
class School < ApplicationRecord

  belongs_to :commune

  # has_many :students
  # , class_name: 'Student', foreign_key: 'student_id'
end

app/models/student.rb
class Student < ApplicationRecord

  belongs_to :tutor, class_name: 'User', foreign_key: 'user_id'
  # belongs_to :commune

  # belongs_to :commune, class_name: 'Commune', foreign_key: 'commune_id'
  # belongs_to :school, class_name: 'School', foreign_key: 'school_id'

  mount_uploader :image, ImageUploader

  geocoded_by :address
  after_validation :geocode

end

app/models/trip.rb
class Trip < ApplicationRecord
end

app/models/tutor.rb
class Tutor < User

  has_many :students, class_name: 'Student', foreign_key: 'user_id', dependent: :destroy
  belongs_to :commune 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  enum role: [:tutor, :chofer, :empresa, :coordinador]

  validates :role, presence: true

  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.type = 'Tutor'
    end
  end

end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  before_action :move_point, only: [:coord_logic]



  # GET /students
  # GET /students.json
  def index
    @tutor = current_user
    # @tutors = current_user
    @students = @tutor.students

    # @students = Student.all

    # geolocation #####

    # if user_signed_in?
    #   @students = Student.near(
    #     current_user.address,
    #     0_3,
    #     units: :km
    #   )
    # else
    #   @students = @tutor.students
    #   # @students = Student.all
    # end

    @students = @tutor.students
    # @students = Student.all
    @hash = Gmaps4rails.build_markers(@students) do |student, marker|
      marker.lat student.latitude
      marker.lng student.longitude
    end
  end

  def coord_logic

    Point.all.each do |point|
    point.latitude
    point.longitude
    point.save
  end

  end

  # 10.times do
  #   Student.all
  #    Student.all.each do |student|
  #      student.latitude += 1
  #    student.longitude += 1
  #   student.save
  #    end
  #  sleep 10
  # end


  def move_point

    # student1 = Student.first
    # # 10.times do
    # student1.latitude += 0.005
    # student1.longitude += 0.005
    # student1.save!
    # #   sleep 1
    # # end
    #
    # student2 = Student.second
    # student2.latitude += 0.005
    # student2.longitude += 0.005
    # student2.save!

    point = Point.all

    Point.all.each do |point|
    point.latitude += 0.0005
    point.longitude += 0.0005
    point.save
  end




  end



  def get_location
    # @tutor = current_user
    # @students = @tutor.students
    @points = Point.all
    @hash = Gmaps4rails.build_markers(@points) do |point, marker|
      marker.lat point.latitude
      marker.lng point.longitude
    end

  end

  # def find_address
  #   latitude = params[:latitude]
  #   longitude = params[:longitude]
  #
  #   address = Geocoder.address([latitude, longitude])
  #
  #   render json: address.to_json
  # end

  #############################

  # GET /students/1
  # GET /students/1.json
  def show
  end

  # GET /students/new
  def new
    @tutor = current_user
    @student = Student.new
    @commune = Commune.all
  end

  # GET /students/1/edit
  def edit
    @commune = Commune.all
  end

  # POST /students
  # POST /students.json
  def create
    if current_user
      @student = Student.new(student_params)

      @student.tutor = current_user


      # @student.school_id = School.find(params[:student][:school_id]).id

      respond_to do |format|
        if @student.save
          format.html { redirect_to tutor_students_path, notice: 'Student was successfully created.' }
          format.json { render :show, status: :created, location: @student }
        else
          format.html { render :new, notice: 'faltan datos'}
          format.json { render json: @student.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to tutor_students_path, alert: 'Debes completar tu perfil antes de crear estudiantes!'
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to tutor_students_path, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy

    respond_to do |format|
      format.html { redirect_to tutor_students_path(current_user), notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.require(:student).permit(:image, :rut, :password, :email, :name, :lastname, :surname, :address, :commune_id, :state, :city, :country, :phone, :school_id, :level, :course)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: [@tutor, @student], url: tutor_students_path(current_user), local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :student_image %>
  </div>

  <div class="field">
    <%= form.label :rut %>
    <%= form.text_field :rut, id: :student_rut %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :student_name %>
  </div>

  <div class="field">
    <%= form.label :lastname %>
    <%= form.text_field :lastname, id: :student_lastname %>
  </div>

  <!-- <div class="field">
    <%= form.label :surname %>
    <%= form.text_field :surname, id: :student_surname %>
  </div> -->

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :student_address %>
  </div>

  <!-- <div class="field">
    <%= form.label :commune %>
    <%= form.select :commune_id, @commune.pluck(:name, :id) %>
  </div> -->
<!--
  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state, id: :student_state %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :student_city %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country, id: :student_country %>
  </div> -->

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :student_phone %>
  </div>

  <div class="field">
    <%= form.label :school %>
    <%= form.text_field  :school , id: :student_school %>
  </div>

  <div class="field">
    <%= form.label :level %>
    <%= form.text_field :level, id: :student_level %>
  </div>

  <div class="field">
    <%= form.label :course %>
    <%= form.text_field :course, id: :student_course %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/students/_geocoding.html.erb
<!-- esto es geocoding -->

<!-- <div id="demo">
</div> -->


<!-- <script>
var x = $('#demo');

if (navigator.geolocation) {
  navigator.geolocation.getCurrentPosition(getAddress);
} else {
  x.innerHTML = "Geolocation is not supported by this browser.";
}
function getAddress(position) {
  var latitude = position.coords.latitude;
  var longitude = position.coords.longitude;
  $.ajax({
    url: '<%= tutor_students_path(current_user) %>',
    type: 'GET',
    dataType: 'json',
    data: {latitude: latitude, longitude: longitude}
  })
  .done(function(data) {
    x.text(data)
  });
};
</script> -->

<div class="container">
  <%= link_to 'Track Map', students_get_location_path , class: 'btn btn-xs btn-info'%>

</div>
<!-- <div class="container">
  <div id="demo"> </div> <button onclick="getLocation()">Try It</button>
</div>


<script type="text/javascript">
var x = document.getElementById("demo");
function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition);
  } else {
    x.innerHTML = "Geolocation is not supported by this browser.";
  }
}
function showPosition(position) {
  x.innerHTML = "Latitude: " + position.coords.latitude +
  "<br>Longitude: " + position.coords.longitude;
}
</script> -->


<div class="container">
  <div class="center-block" align="center">
    <div style='width: 800px;'>
      <div id="map" style='width: 800px; height: 400px;'></div>
    </div>

  </div>

</div>


<script type="text/javascript">
$(document).on('turbolinks:load', function() {
  handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {
      center: new google.maps.LatLng({lat: -33.43, lng: -70.61}),
      zoom: 10
    },
    internal: {
      id: 'map'
    }
  },
  function(){
     markers = handler.addMarkers(<%=raw @hash.to_json %>);
    });
});
</script>

app/views/students/coord_logic.js.erb
console.log('HOLAHOLA!');
location.reload();

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= form_with(model: [@tutor, @student], url:tutor_student_path(current_user, @student), local: true) do |form| %>


<div class="field">
  <%= form.label :image %>
  <%= form.file_field :image, id: :student_image %>
</div>

<div class="field">
  <%= form.label :rut %>
  <%= form.text_field :rut, id: :student_rut %>
</div>

<div class="field">
  <%= form.label :name %>
  <%= form.text_field :name, id: :student_name %>
</div>

<div class="field">
  <%= form.label :lastname %>
  <%= form.text_field :lastname, id: :student_lastname %>
</div>

<div class="field">
  <%= form.label :surname %>
  <%= form.text_field :surname, id: :student_surname %>
</div>

<div class="field">
  <%= form.label :address %>
  <%= form.text_field :address, id: :student_address %>
</div>

<div class="field">
  <%= form.label :commune %>
  <%= form.select :commune_id, @commune.pluck(:name, :id) %>
</div>

<div class="field">
  <%= form.label :state %>
  <%= form.text_field :state, id: :student_state %>
</div>

<div class="field">
  <%= form.label :city %>
  <%= form.text_field :city, id: :student_city %>
</div>

<div class="field">
  <%= form.label :country %>
  <%= form.text_field :country, id: :student_country %>
</div>

<div class="field">
  <%= form.label :phone %>
  <%= form.text_field :phone, id: :student_phone %>
</div>

<div class="field">
  <%= form.label :school %>
  <%= form.text_field :school, id: :student_school %>
</div>

<div class="field">
  <%= form.label :level %>
  <%= form.text_field :level, id: :student_level %>
</div>

<div class="field">
  <%= form.label :course %>
  <%= form.text_field :course, id: :student_course %>
</div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', tutor_student_path(@student) %> |
<%= link_to 'Back', tutor_students_path(current_user) %>

app/views/students/edit.js.erb
alert("jasdakjsdn")
$('#student-table').html("<%= j render 'form' %>")
$('#exampleModal').modal('edit');

app/views/students/get_location.html.erb
<h1>Demo Track</h1>

<div class="container">

  <div style='width: 800px;'>
    <div id="map" style='width: 800px; height: 400px;'></div>
  </div>
</div>

<div id="track-map">
sadasd
</div>

<script type="text/javascript">
$(document).on('turbolinks:load', function() {
  handler = Gmaps.build('Google');
  handler.buildMap({
    provider: {
      center: new google.maps.LatLng({lat: -33.41, lng: -70.56}),
      zoom: 12
    },
    internal: {
      id: 'map'
    }
  },
  function(){
    markers = handler.addMarkers(<%=raw @hash.to_json %>);
  });
});
</script>

<script type="text/javascript">
  $(document).ready(function() {

    var studentMap = setInterval(function () {
      $.ajax({
        url: "<%= students_coord_logic_path %>",
        type:'GET',
        data: {student:{address: 'zzzzzzzzzzzzzzzzz'}}
      })
      .done(function() {
        console.log("success")
        clearInterval (studentMap);
      })
    }, 1000);
  });

</script>

app/views/students/index.html.erb
<div class="text-center">
  <p id="notice"><%= notice %></p>
</div>

<div class="container">
  <div class="jumbotron">
    <%= render 'tutors/index' %>
  </div>
</div>


<br><br>

<div class="container">
  <div class="jumbotron">

    <h1>Mis Estudiantes</h1>

    <div class="row" id="student-table">
      <table >
        <thead>
          <tr>
            <th>Image</th>
            <th>Rut</th>
            <th>Name</th>
            <th>Lastname</th>
            <!-- <th>Surname</th> -->
            <th>Address</th>
            <!-- <th>Commune</th>
            <th>State</th>
            <th>City</th>
            <th>Country</th> -->
            <!-- <th>Phone</th> -->
            <th>School</th>
            <th>Level</th>
            <th>Course</th>
            <th>User ID</th>
            <th colspan="3"></th>
          </tr>
        </thead>

        <tbody>
          <% @students.each do |student| %>
          <tr>
            <td><%= image_tag student.image.thumb %></td>
            <td><%= student.rut %></td>
            <td><%= student.name %></td>
            <td><%= student.lastname %></td>
            <!-- <td><%#= student.surname %></td> -->
            <td><%= student.address %></td>
            <!-- <td><%#= student.commune.name %></td> -->
            <!-- <td><%#= student.state %></td>
            <td><%#= student.city %></td>
            <td><%#= student.country %></td> -->
            <!-- <td><%#= student.phone %></td> -->
            <td><%= student.school %></td>
            <td><%= student.level %></td>
            <td><%= student.course %></td>
            <td><%= student.id %></td>
            <td><%= link_to 'Show', tutor_student_path(current_user, student) , class: 'btn btn-xs btn-info'%></td>
            <td><%= link_to 'Edit', edit_tutor_student_path(current_user, student) , class: 'btn btn-xs btn-warning'%></td>
            <td><%= link_to 'Destroy', tutor_student_path(current_user, student), method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-xs btn-danger' %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <br>
      <%= link_to 'New Student', new_tutor_student_path , class: 'btn btn-xs btn-success'%>


    </div>


  </div>


</div>




<div class="container">
  <div class="jumbotron">
    <%= render 'students/geocoding' %>
  </div>
</div>

app/views/students/index.js.erb
console.log("hola")

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', tutor_students_path(current_user)  %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @student.image.thumb %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @student.rut %>
</p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
</p>

<p>
  <strong>Lastname:</strong>
  <%= @student.lastname %>
</p>
<!--
<p>
  <strong>Surname:</strong>
  <%#= @student.surname %>
</p> -->

<p>
  <strong>Address:</strong>
  <%= @student.address %>
</p>
<!--
<p>
  <strong>Commune:</strong>
  <%#= @student.commune.name %>
</p>

<p>
  <strong>State:</strong>
  <%#= @student.state %>
</p>

<p>
  <strong>City:</strong>
  <%#= @student.city %>
</p>

<p>
  <strong>Country:</strong>
  <%#= @student.country %>
</p> -->

<p>
  <strong>Phone:</strong>
  <%= @student.phone %>
</p>

<p>
  <strong>School:</strong>
  <%= @student.school %>
</p>

<p>
  <strong>Level:</strong>
  <%= @student.level %>
</p>

<p>
  <strong>Course:</strong>
  <%= @student.course %>
</p>

<!-- <p>
  <strong>User:</strong>
  <%#= @student.student_id %>
</p> -->

<%= link_to 'Edit', edit_tutor_student_path(@student) %> |
<%= link_to 'Back', tutor_students_path(current_user) %>