config/routes.rb
Rails.application.routes.draw do

  resources :coordinators, only: [:index, :show, :edit, :update]

  resources :enterprises, only: [:index, :show, :edit, :update] do
    resources :drivers
    resources :cars, except: :index
    resources :car_drivers
  end


  resources :tutors, only: [:index, :show, :edit, :update] do
    # get 'students/get_location'
    resources :students do
      resources :trips, only: :index
    end
  end

  root 'homes#index'

  get 'students/get_location'

  get 'students/coord_logic'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
  :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

  belongs_to :enterprise, class_name: 'Enterprise', foreign_key: 'user_id'

end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :region
  # has_many :tutors
  # has_many :students

  # has_many :students
  # , class_name: 'Student', foreign_key: 'student_id'

end

app/models/coordinator.rb
class Coordinator < User

  # has_many :schools

end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/driver.rb
class Driver < User

  belongs_to :enterprise, class_name: 'Enterprise', foreign_key: 'enterprise_id'

  # has_many :car_drivers, class_name: 'CarDriver', foreign_key: 'driver_id'

  # has_many :cars, through: :car_drivers

  # has_many :schools


end

app/models/enterprise.rb
class Enterprise < User

  has_many :drivers, class_name: 'Driver', foreign_key: 'enterprise_id', dependent: :destroy

  has_many :cars, class_name: 'Car', foreign_key: 'user_id', dependent: :destroy

  # has_many :car_drivers, class_name: 'CarDriver', foreign_key: 'driver_id', dependent: :destroy

  # has_many :schools



end

app/models/point.rb
class Point < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
end

app/models/school.rb
class School < ApplicationRecord

  belongs_to :commune

  # has_many :students
  # , class_name: 'Student', foreign_key: 'student_id'
end

app/models/student.rb
class Student < ApplicationRecord

  belongs_to :tutor, class_name: 'User', foreign_key: 'user_id'
  # belongs_to :commune

  # belongs_to :commune, class_name: 'Commune', foreign_key: 'commune_id'
  # belongs_to :school, class_name: 'School', foreign_key: 'school_id'

  mount_uploader :image, ImageUploader

  geocoded_by :address
  after_validation :geocode

end

app/models/trip.rb
class Trip < ApplicationRecord
end

app/models/tutor.rb
class Tutor < User

  has_many :students, class_name: 'Student', foreign_key: 'user_id', dependent: :destroy
  belongs_to :commune 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  enum role: [:tutor, :chofer, :empresa, :coordinador]

  validates :role, presence: true

  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.type = 'Tutor'
    end
  end

end

app/controllers/coordinators_controller.rb
class CoordinatorsController < ApplicationController

  before_action :set_coordinator, only: [:show, :edit, :update]
  before_action :authenticate_user!


  def index
    @coordinator = current_user

    #para buscar la info de autos y choferes asociados al coordinador
    # @drivers = @enterprise.drivers
    # @cars = @enterprise.cars

    #para buscar la info de alumnos y tutores asociados al coordinador
    # @students = @tutor.students
  end

  def show
  end

  def edit
  end

  def update
    respond_to do |format|
      if @coordinator.update(coordinator_params)
        format.html { redirect_to coordinator_path(@coordinator), notice: 'Coordinator was successfully updated.' }
        format.json { render :show, status: :ok, location: @coordinator }
      else
        format.html { render :edit }
        format.json { render json: @coordinator.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_coordinator
    @coordinator = Coordinator.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def coordinator_params
    params.require(:coordinator).permit(:image, :rut, :name, :email, :r_legal, :rut_legal, :giro, :address, :commune, :state, :city, :country, :phone, :school, :role, :info_emergency, :user_id)
  end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/coordinators_helper.rb
module CoordinatorsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/coordinators/edit.html.erb
<h1>Editing coordinator</h1>

<%= form_with(model: [@coordinator],url: coordinator_path(current_user), local: true) do |form| %>
<% if @coordinator.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(coordinator.errors.count, "error") %> prohibited this coordinator from being saved:</h2>

    <ul>
    <% coordinator.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>


  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image, id: :coordinator_image %>
  </div>

  <div class="field">
    <%= form.label :rut %>
    <%= form.text_field :rut, id: :coordinator_rut %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :coordinator_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :coordinator_email %>
  </div>

  <div class="field">
    <%= form.label :r_legal %>
    <%= form.text_field :r_legal, id: :coordinator_r_legal %>
  </div>

  <div class="field">
    <%= form.label :rut_legal %>
    <%= form.text_field :rut_legal, id: :coordinator_rut_legal %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :coordinator_address %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :coordinator_phone %>
  </div>

  <div class="field">
    <%= form.label :school %>
    <%= form.text_field :school, id: :coordinator_school %>
  </div>

  <div class="field">
    <%= form.label :coordinator %>
    <%= form.text_field :coordinator, id: :coordinator_coordinator %>
  </div>

  <div class="field">
    <%= form.label :role %>
    <%= form.text_field :role, id: :coordinator_role %>
  </div>

  <div class="field">
    <%= form.label :info_emergency %>
    <%= form.text_field :info_emergency, id: :coordinator_info_emergency %>
  </div>

  <div class="field">
    <%= form.label :coordinator_id %>
    <%= form.text_field :id, id: :coordinator_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>


<%= link_to 'Back', coordinators_path(current_user) %>

app/views/coordinators/index.html.erb
<h1>Mi Datos de coordinador</h1>

<table>
  <thead>
    <tr>
      <th>Foto</th>
      <th>Rut</th>
      <th>Nombre</th>
      <th>Email</th>
      <th>Representante Legal</th>
      <th>Rut Representante Legal</th>
      <th>Dirección</th>
      <th>Teléfono</th>
      <th>Colegio</th>
      <th>Coordinador</th>
      <th>Rol</th>
      <th>Informacion de Emergencia</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
      <tr>
        <td><%= image_tag @coordinator.image.thumb %></td>
        <td><%= @coordinator.rut %></td>
        <td><%= @coordinator.name %></td>
        <td><%= @coordinator.email %></td>
        <td><%= @coordinator.r_legal %></td>
        <td><%= @coordinator.rut_legal %></td>
        <td><%= @coordinator.address %></td>
        <td><%= @coordinator.phone %></td>
        <td><%= @coordinator.school %></td>
        <td><%= @coordinator.coordinator %></td>
        <td><%= @coordinator.role %></td>
        <td><%= @coordinator.info_emergency %></td>
        <td><%= link_to 'Show', coordinator_path(current_user) %></td>
        <td><%= link_to 'Editar', edit_coordinator_path(current_user) %></td>
      </tr>

  </tbody>
</table>

<br>
<%= render "students/geocoding" %>

app/views/coordinators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Image:</strong>
  <%= image_tag @coordinator.image.thumb %>
</p>

<p>
  <strong>Rut:</strong>
  <%= @coordinator.rut %>
</p>

<p>
  <strong>Name:</strong>
  <%= @coordinator.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @coordinator.email %>
</p>

<p>
  <strong>Representante Legal:</strong>
  <%= @coordinator.r_legal %>
</p>

<p>
  <strong>Rut Representante Legal:</strong>
  <%= @coordinator.rut_legal %>
</p>

<p>
  <strong>Address:</strong>
  <%= @coordinator.address %>
</p>

<p>
  <strong>Telefono:</strong>
  <%= @coordinator.phone %>
</p>

<p>
  <strong>coordinador:</strong>
  <%= @coordinator.school %>
</p>

<p>
  <strong>Coordinador:</strong>
  <%= @coordinator.coordinator %>
</p>

<p>
  <strong>Rol:</strong>
  <%= @coordinator.role %>
</p>

<p>
  <strong>Info_emergency:</strong>
  <%= @coordinator.info_emergency %>
</p>


<%= link_to 'Edit', edit_coordinator_path(current_user)  %> |
<%= link_to 'Back', coordinators_path(current_user) %>