config/routes.rb
Rails.application.routes.draw do

  resources :coordinators, only: [:index, :show, :edit, :update]

  resources :enterprises, only: [:index, :show, :edit, :update] do
    resources :drivers
    resources :cars, except: :index
    resources :car_drivers
  end


  resources :tutors, only: [:index, :show, :edit, :update] do
    # get 'students/get_location'
    resources :students do
      resources :trips, only: :index
    end
  end

  root 'homes#index'

  get 'students/get_location'

  get 'students/coord_logic'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
  :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

end

app/models/car.rb
class Car < ApplicationRecord

  belongs_to :enterprise, class_name: 'Enterprise', foreign_key: 'user_id'

end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :region
  # has_many :tutors
  # has_many :students

  # has_many :students
  # , class_name: 'Student', foreign_key: 'student_id'

end

app/models/coordinator.rb
class Coordinator < User

  # has_many :schools

end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/driver.rb
class Driver < User

  belongs_to :enterprise, class_name: 'Enterprise', foreign_key: 'enterprise_id'

  # has_many :car_drivers, class_name: 'CarDriver', foreign_key: 'driver_id'

  # has_many :cars, through: :car_drivers

  # has_many :schools


end

app/models/enterprise.rb
class Enterprise < User

  has_many :drivers, class_name: 'Driver', foreign_key: 'enterprise_id', dependent: :destroy

  has_many :cars, class_name: 'Car', foreign_key: 'user_id', dependent: :destroy

  # has_many :car_drivers, class_name: 'CarDriver', foreign_key: 'driver_id', dependent: :destroy

  # has_many :schools



end

app/models/point.rb
class Point < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
end

app/models/school.rb
class School < ApplicationRecord

  belongs_to :commune

  # has_many :students
  # , class_name: 'Student', foreign_key: 'student_id'
end

app/models/student.rb
class Student < ApplicationRecord

  belongs_to :tutor, class_name: 'User', foreign_key: 'user_id'
  # belongs_to :commune

  # belongs_to :commune, class_name: 'Commune', foreign_key: 'commune_id'
  # belongs_to :school, class_name: 'School', foreign_key: 'school_id'

  mount_uploader :image, ImageUploader

  geocoded_by :address
  after_validation :geocode

end

app/models/trip.rb
class Trip < ApplicationRecord
end

app/models/tutor.rb
class Tutor < User

  has_many :students, class_name: 'Student', foreign_key: 'user_id', dependent: :destroy
  belongs_to :commune 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  enum role: [:tutor, :chofer, :empresa, :coordinador]

  validates :role, presence: true

  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.type = 'Tutor'
    end
  end

end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rapuapp</title>
  <%= csrf_meta_tags %>
  <!-- bootstrap cdn -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

  <!-- Responsive meta tag -->

  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<!-- instalacion de jquery via yarn /// volver a revisar-->
  <!-- ### cdn jquery -->
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

  <%= render  'shared/navbar'%>

  <p class="navbar-text pull-right">
    <% if user_signed_in? %>
    Loggedado como  <strong><%= current_user.email %></strong>.
    <%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link' %>
    <%= link_to "Salir", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
    <%= link_to "Registrate", new_user_registration_path, :class => 'navbar-link'  %>
    <%= link_to "Ingresa", new_user_session_path, :class => 'navbar-link'  %>
    <% end %>
  </p>


  <%= yield %>

  <!-- bootstrap cdn -->

  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

  <!-- googlemaps cdn -->

  <script src="//maps.google.com/maps/api/js?key=AIzaSyAMmQclWGCb1EkxQH_TGieHvGzGgCNValk"></script>
  <script src="//cdn.rawgit.com/mahnunchik/markerclustererplus/master/dist/markerclusterer.min.js"></script>
  <script src='//cdn.rawgit.com/printercu/google-maps-utility-library-v3-read-only/master/infobox/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->



</body>
</html>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarTogglerDemo01">

  <a class="navbar-brand" href="<%= root_path %>">Mi RapuApp</a>
  <% if user_signed_in? %>

  <% if current_user.tutor? %>
  <a class="navbar-brand" href="<%= tutor_students_path(current_user) %>">Panel de Control ::: Tutor</a>

  <% elsif current_user.chofer? %>
   <a class="navbar-brand" href="<%#= enterprise_driver_path(current_user) %>">Panel de Control ::: Chofer</a>

  <% elsif current_user.empresa? %>
   <a class="navbar-brand" href="<%= enterprise_drivers_path(current_user) %>">Panel de Control ::: Empresa</a>

  <% elsif current_user.coordinador? %>
   <a class="navbar-brand" href="<%= coordinators_path %>">Panel de Control ::: coordinador</a>

  <% elsif current_user.alumno? %>
   <a class="navbar-brand" href="<%= tutors_path %>">Panel de Control ::: Alumno</a>


  <% end %>
  <% end %>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarNav">
    <% if user_signed_in? %>
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <strong><%= link_to current_user.email, '#', class: 'nav-link' %></strong>
      </li>
      <li class="nav-item">
        <%= link_to 'Cerrar sesión', destroy_user_session_path, method: :delete, class: 'nav-link' %>
        <%= link_to 'Editar Perfil', edit_user_registration_path, :class => 'navbar-link' %>

      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to 'Iniciar Sesión', new_user_session_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to 'Registrarse', new_user_registration_path, class: 'nav-link' %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>
<p id="notice"><%= notice %></p>