config/routes.rb
Rails.application.routes.draw do

  resources :coordinators, only: [:index, :show, :edit, :update]

  resources :enterprises, only: [:index, :show, :edit, :update] do
    resources :drivers
    resources :cars, except: :index
    resources :car_drivers
  end


  resources :tutors, only: [:index, :show, :edit, :update] do
    # get 'students/get_location'
    resources :students do
      resources :trips, only: :index
    end
  end

  root 'homes#index'

  get 'students/get_location'

  get 'students/coord_logic'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)


  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: "users/registrations",
    omniauth_callbacks: 'users/omniauth_callbacks'
  }


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
  :recoverable, :rememberable, :trackable, :validatable

  mount_uploader :image, ImageUploader

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/car.rb
class Car < ApplicationRecord

  belongs_to :enterprise, class_name: 'Enterprise', foreign_key: 'user_id'

end

app/models/commune.rb
class Commune < ApplicationRecord
  belongs_to :region
  # has_many :tutors
  # has_many :students

  # has_many :students
  # , class_name: 'Student', foreign_key: 'student_id'

end

app/models/coordinator.rb
class Coordinator < User

  # has_many :schools

end

app/models/country.rb
class Country < ApplicationRecord
end

app/models/driver.rb
class Driver < User

  belongs_to :enterprise, class_name: 'Enterprise', foreign_key: 'enterprise_id'

  # has_many :car_drivers, class_name: 'CarDriver', foreign_key: 'driver_id'

  # has_many :cars, through: :car_drivers

  # has_many :schools


end

app/models/enterprise.rb
class Enterprise < User

  has_many :drivers, class_name: 'Driver', foreign_key: 'enterprise_id', dependent: :destroy

  has_many :cars, class_name: 'Car', foreign_key: 'user_id', dependent: :destroy

  # has_many :car_drivers, class_name: 'CarDriver', foreign_key: 'driver_id', dependent: :destroy

  # has_many :schools



end

app/models/point.rb
class Point < ApplicationRecord
end

app/models/region.rb
class Region < ApplicationRecord
  belongs_to :country
end

app/models/school.rb
class School < ApplicationRecord

  belongs_to :commune

  # has_many :students
  # , class_name: 'Student', foreign_key: 'student_id'
end

app/models/student.rb
class Student < ApplicationRecord

  belongs_to :tutor, class_name: 'User', foreign_key: 'user_id'
  # belongs_to :commune

  # belongs_to :commune, class_name: 'Commune', foreign_key: 'commune_id'
  # belongs_to :school, class_name: 'School', foreign_key: 'school_id'

  mount_uploader :image, ImageUploader

  geocoded_by :address
  after_validation :geocode

end

app/models/trip.rb
class Trip < ApplicationRecord
end

app/models/tutor.rb
class Tutor < User

  has_many :students, class_name: 'Student', foreign_key: 'user_id', dependent: :destroy
  belongs_to :commune 

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable, :validatable, :omniauthable, :omniauth_providers => [:facebook]

  enum role: [:tutor, :chofer, :empresa, :coordinador]

  validates :role, presence: true

  mount_uploader :image, ImageUploader

  def self.from_omniauth(auth)
    where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
      user.email = auth.info.email
      user.password = Devise.friendly_token[0,20]
      user.name = auth.info.name
      user.type = 'Tutor'
    end
  end

end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :set_car, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /cars
  # GET /cars.json
  def index

    @enterprise = current_user
    @cars = @enterprise.cars

    #logeando vista drivers con autos
    # @drivers = @enterprise.drivers
    # @cars = Car.all
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @enterprise = current_user
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create

    if current_user
      @car = Car.new(car_params)
      @car.enterprise = current_user

      respond_to do |format|
        if @car.save
          format.html { redirect_to enterprise_drivers_path, notice: 'Car was successfully created.' }
          format.json { render :show, status: :created, location: @car }
        else
          format.html { render :new }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to enterprise_drivers_path, alert: 'Debes completar tu perfil antes de crear Vehiculos!'
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to enterprise_drivers_path, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to enterprise_drivers_path(current_user), notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_car
    @car = Car.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def car_params
    params.require(:car).permit(:type_car, :brand, :model, :year, :color, :plate, :tech_rev, :nation_registry, :user_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/drivers_helper.rb
module DriversHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/tutors_helper.rb
module TutorsHelper
end

app/views/cars/_form.html.erb
<%= form_with(model: [@enterprise, @car], url: enterprise_cars_path(current_user), local: true) do |form| %>
  <% if car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% car.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :type_car %>
    <%= form.text_field :type_car, id: :car_type_car %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :car_brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :car_model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year, id: :car_year %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :car_color %>
  </div>

  <div class="field">
    <%= form.label :plate %>
    <%= form.text_field :plate, id: :car_plate %>
  </div>

  <div class="field">
    <%= form.label :tech_rev %>
    <%= form.check_box :tech_rev, id: :car_tech_rev %>
  </div>

  <div class="field">
    <%= form.label :nation_registry %>
    <%= form.check_box :nation_registry, id: :car_nation_registry %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :car_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/cars/_index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Type car</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Year</th>
      <th>Color</th>
      <th>Plate</th>
      <th>Tech rev</th>
      <th>Nation registry</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.type_car %></td>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.color %></td>
        <td><%= car.plate %></td>
        <td><%= car.tech_rev %></td>
        <td><%= car.nation_registry %></td>
        <td><%= car.user_id %></td>
        <td><%= link_to 'Show', enterprise_car_path(current_user, car) %></td>
        <td><%= link_to 'Edit', edit_enterprise_car_path(current_user, car) %></td>
        <td><%= link_to 'Destroy', enterprise_car_path(current_user, car), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Car', new_enterprise_car_path %>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= form_with(model: [@enterprise, @car], url: enterprise_car_path(current_user), local: true) do |form| %>


  <div class="field">
    <%= form.label :type_car %>
    <%= form.text_field :type_car, id: :car_type_car %>
  </div>

  <div class="field">
    <%= form.label :brand %>
    <%= form.text_field :brand, id: :car_brand %>
  </div>

  <div class="field">
    <%= form.label :model %>
    <%= form.text_field :model, id: :car_model %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year, id: :car_year %>
  </div>

  <div class="field">
    <%= form.label :color %>
    <%= form.text_field :color, id: :car_color %>
  </div>

  <div class="field">
    <%= form.label :plate %>
    <%= form.text_field :plate, id: :car_plate %>
  </div>

  <div class="field">
    <%= form.label :tech_rev %>
    <%= form.check_box :tech_rev, id: :car_tech_rev %>
  </div>

  <div class="field">
    <%= form.label :nation_registry %>
    <%= form.check_box :nation_registry, id: :car_nation_registry %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :car_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<%= link_to 'Show', enterprise_car_path(@car) %> |
<%= link_to 'Back', enterprise_drivers_path(current_user) %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cars</h1>

<table>
  <thead>
    <tr>
      <th>Type car</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Year</th>
      <th>Color</th>
      <th>Plate</th>
      <th>Tech rev</th>
      <th>Nation registry</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cars.each do |car| %>
      <tr>
        <td><%= car.type_car %></td>
        <td><%= car.brand %></td>
        <td><%= car.model %></td>
        <td><%= car.year %></td>
        <td><%= car.color %></td>
        <td><%= car.plate %></td>
        <td><%= car.tech_rev %></td>
        <td><%= car.nation_registry %></td>
        <td><%= car.user %></td>
        <td><%= link_to 'Show', car %></td>
        <td><%= link_to 'Edit', edit_car_path(car) %></td>
        <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%#= link_to 'New Car', new_car_path %>

app/views/cars/new.html.erb
<h1>New Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Back', enterprise_drivers_path(current_user) %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type car:</strong>
  <%= @car.type_car %>
</p>

<p>
  <strong>Brand:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Color:</strong>
  <%= @car.color %>
</p>

<p>
  <strong>Plate:</strong>
  <%= @car.plate %>
</p>

<p>
  <strong>Tech rev:</strong>
  <%= @car.tech_rev %>
</p>

<p>
  <strong>Nation registry:</strong>
  <%= @car.nation_registry %>
</p>

<p>
  <strong>User:</strong>
  <%= @car.user_id %>
</p>

<%= link_to 'Edit', edit_enterprise_car_path(@car) %> |
<%= link_to 'Back', enterprise_drivers_path(current_user) %>